Task2.3
fujoshik/Tasks pull request #6
Opened 2024-04-30 19:44 UTC by fujoshik

2024-05-02 13:03 UTC, IgorKheidorov requested changes

2024-05-02 13:03 UTC, IgorKheidorov commented on Task 2/Task2.3/Trainings/Interfaces/ITraining.cs
> +{
Interface without methods?

2024-05-02 13:03 UTC, IgorKheidorov commented on Task 2/Task2.3/Trainings/Training.cs
> +        private int _trainingsCount;
BaseTraining[] will be ok, but not perfect.\
The right structure is Training : TrainingEnity (->Description inside)
PracticalLesson: BaseTraing: TrainingEntity

And all entities implements IClonable interface

2024-05-04 07:52 UTC, fujoshik commented on Task 2/Task2.3/Trainings/Interfaces/ITraining.cs
> +{
Fixed

2024-05-04 07:52 UTC, fujoshik commented on Task 2/Task2.3/Trainings/Training.cs
> +        private int _trainingsCount;
Fixed

2024-05-20 05:53 UTC, merged